name: ğŸ—ï¸ Build PR

on:
  pull_request: ~

env:
  alpine: "3.21"
  version: "v3"
  stream: "pr-${{ github.event.pull_request.number }}"

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ '20', '22', '24' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ‹ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ—ï¸ Build  Docker image
        uses: docker/bake-action@v6
        env:
          ALPINE_VERSION: ${{ env.alpine }}
          NODE_VERSION: ${{ matrix.node }}
          STREAM: ${{ env.stream }}
          VERSION: ${{ env.version }}

      - name: Test Docker image
        run: |
          echo make test NODE_VERSION=${{ matrix.node }}  VERSION=${{ env.version }} STREAM=${{ env.stream }}
