name: ğŸ—ï¸ Build PR

on:
  pull_request: ~

jobs:
  build:
    uses: ./.github/workflows/build-push.yml
    with:
      stream: "pr-${{ github.event.pull_request.number }}"
      push: true
    secrets: inherit
