name: ğŸ—ï¸ Build PR

on:
  pull_request: ~

jobs:
  build:
    uses: ./.github/workflows/build-push.yml
    with:
      stream: "pr-${{ github.event.pull_request.number }}"
      push: false
    secrets: inherit
#  build:
#    name: Build Docker image
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        node: [ '20', '22', '24' ]
#
#    steps:
#      - name: ğŸ”‘ Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: ğŸ”‘ Log in to the GitHub Container Registry
#        uses: docker/login-action@v3
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: ğŸ‹ Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: ğŸ—ï¸ Build and push Docker image
#        uses: docker/bake-action@v6
#        env:
#          NODE_VERSION: ${{ matrix.node }}
#          STREAM: ${{ env.stream }}
#        with:
#          pull: true
#          no-cache: true
