name: ğŸ—ï¸ Build and Push

on:
  workflow_call:
    inputs:
      runs_on:
        type: string
        default: ubuntu-latest
        description: The image to run the jobs.
      platforms:
        type: string
        default: linux/amd64,linux/arm64
        description: The target platforms for the Docker image.
      stream:
        type: string
        default: latest
        description: The stream to build (e.g latest or stable).
      version:
        type: string
        default: v3
        description: The major version to use in the Docker image.
      alpine:
        type: string
        default: '3.21'
        description: The Alpine version to use in the Docker image.
      push:
        type: boolean
        default: false
        description: Whether to push the built image to the registry.

    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    name: Build Docker image
    runs-on: ${{ inputs.runs_on }}
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        node: [ '20', '22', '24' ]

    steps:
      - name: ğŸ”‘ Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ğŸ”‘ Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ‹ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ—ï¸ Build and push Docker image
        uses: docker/bake-action@v6
        env:
          ALPINE_VERSION: ${{ inputs.alpine }}
          NODE_VERSION: ${{ matrix.node }}
          STREAM: ${{ inputs.stream }}
          VERSION: ${{ inputs.version }}
        with:
          push: ${{ inputs.push }}
